language: c

os:
	- linux
	- osx


addons:
	homebrew:
		packages:
		- sdl2
	apt:
    	packages:
		- libsdl2-2.0-9
    	- libsdl2-dev

script: make

notifications:
  slack: 42born2code:6JQ1d0KBj9Vggul0KNL9p0fW
