---
addons:
  homebrew:
    packages:
      - sdl2
      - sdl2_image
      - if [ $TRAVIS_BRANCH == "master" ]; then doxygen; fi
      - if [ $TRAVIS_BRANCH == "master" ]; then graphviz; fi
    update: true
branches:
  except:
    - Sam_wip
    - gh-pages
deploy:
  github_token: $GH_REPO_TOKEN
  local_dir: $TRAVIS_BUILD_DIR/docs/html
  provider: pages
  skip_cleanup: true
  true:
    branch: master
install:
  - "if [ $TRAVIS_OS_NAME == \"linux\" ]; then sudo sh resources/script/install_sdl.sh; fi"
language: c
matrix:
  allow_failures:
    -
      os: linux
notifications:
  slack: "42born2code:6JQ1d0KBj9Vggul0KNL9p0fW"
os:
  - osx
script:
  - make test
  - if [ $TRAVIS_BRANCH == "master" ]; then doxygen Doxyfile; fi
sudo: required
