os:
# - linux
- osx
language: c
sudo: required
addons:
  homebrew:
    packages:
	- doxygen
    - sdl2
    - sdl2_image
    update: true
install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
    sudo sh resources/script/install_sdl.sh;
    fi
script:
  - make test
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master

# Notifications :
matrix:
  allow_failures:
    - os: linux
notifications:
  slack: 42born2code:6JQ1d0KBj9Vggul0KNL9p0fW

# blocklist
branches:
  except:
  - Sam_wip
