os:
- linux
- osx
language: c
addons:
  homebrew:
    packages:
    - sdl2
install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
    echo "linux"
    fi
script: make

# Notifications :
matrix:
  allow_failures:
    - os: linux
notifications:
  slack: 42born2code:6JQ1d0KBj9Vggul0KNL9p0fW
