os:
- linux
- osx
language: c
addons:
  homebrew:
    packages:
    - sdl2
install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
    travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.9.tar.gz | tar xz;
	cd SDL2-2.0.9;
	./configure;
	make;
  	sudo make install;
	cd ..;
    fi
script: make

# Notifications :
matrix:
  allow_failures:
    - os: linux
notifications:
  slack: 42born2code:6JQ1d0KBj9Vggul0KNL9p0fW
