os:
- linux
- osx
language: c
addons:
  homebrew:
    packages:
    - sdl2
  apt:
    packages:
    - libsdl2-dev
    # - libsdl2-2.0.9 (this dont works so need to dll the sources and install)
script: make

notifications:
  slack: 42born2code:6JQ1d0KBj9Vggul0KNL9p0fW
